blank_issues_enabled: true
contact_links:
  - name: Discussions & Support
    url: https://aspirepress.org/slack/
    about: You can ask general questions or give feedback on the AspirePress community.
