name: Run PHPUnit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.4', '8.3']
    services:
      database:
        image: mysql:latest
        env:
          MYSQL_DATABASE: wordpress_tests
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: $
          tools: phpunit-polyfills:1.1

      - name: Setup tests
        run: bash bin/install-wp-tests.sh wordpress_tests root root 127.0.0.1 latest true

      - name: Run tests
        run: phpunit
